AWSTemplateFormatVersion: "2010-09-09"
Description: Setup Infra

Parameters:
  Owner:
    Type: String
  Service:
    Type: String

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Configuration
        Parameters:
          - Owner
          - Service
    ParameterLabels:
      Owner:
        default: Owner
      Service:
        default: Service

Resources:
  Admin:
    Type: AWS::IAM::User
    DeletionPolicy: Retain
    Properties:
      UserName: !Sub ${Owner}-${Service}
      Path: "/"

  AdminPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: Admin
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: "*"
            Resource: "*"
      Users:
        - !Ref Admin

  ArtifactStoreBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub ${Owner}-${Service}-artifact
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
